title: observer
description: 살아낸 것을 독자가 읽을 수 있는 이야기로 옮기는 공간

url: https://koogk7.github.io
baseurl: /observer

theme: minima
markdown: kramdown
highlighter: rouge
permalink: /:title/

minima:
  skin: auto

author:
  name: observer

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - LICENSE
  - .editorconfig
  - .gitignore
